from __future__ import annotations

from dataclasses import dataclass, field

from ..domain import EvaluationResult, KernelProgram, ProposalStatus

'''
Note on two Edge classes - RealizationEdge, StrategyEdge

All possible semantic actions are strategies and represented by StrategyEdge instances.

Since the application of strategies is stochastic (i.e. dynamics are stochastic), we can get multiple realizations or outcomes. Each concrete outcome is represented by an instance of RealizationEdge.

StrategyEdge instances are chosen by PUCT.

RealizationEdge are generated by either generating a new candidate if pw allows, or choosing among existing ones with UCB.

  StrategyEdge selected by PUCT
  ├── PW allows expansion
  │   └── generate valid candidate → create/reuse
  RealizationEdge
  └── PW saturated
      └── UCB selects existing RealizationEdge

'''


@dataclass(slots=True)
class RealizationEdge:
    child_id: str
    descents: int = 0
    value_sum: float = 0.0

    @property
    def q_mean(self) -> float:
        return self.value_sum / self.descents if self.descents else 0.0


@dataclass(slots=True)
class StrategyEdge:
    strategy_id: str
    prior: float
    visits: int = 0 #number of PUCT choices to this edge
    value_sum: float = 0.0
    q_max: float = float("-inf")
    realizations: dict[str, RealizationEdge] = field(default_factory=dict)
    proposal_count: int = 0 #number of pw cands incl. INVALID ones
    generation_attempt_count: int = 0
    repair_generation_count: int = 0
    valid_proposal_count: int = 0
    invalid_proposal_count: int = 0

    @property
    def q_mean(self) -> float:
        return self.value_sum / self.visits if self.visits else 0.0


@dataclass(slots=True)
class SearchNode:
    id: str
    evaluation: EvaluationResult
    actions: dict[str, StrategyEdge] = field(default_factory=dict)
    profile: dict[str, object] | None = None #derived from ncu

    def __post_init__(self) -> None:
        if self.evaluation.status != ProposalStatus.VALID:
            #All SearchNode instances have VALID status i.e. shhould never get here - defensive invariant
            raise ValueError("search nodes require valid evaluations")

    @property
    def state_key(self) -> str:
        assert self.evaluation.state_key is not None
        return self.evaluation.state_key

    @property
    def program(self) -> KernelProgram:
        assert self.evaluation.program is not None
        return self.evaluation.program

    @property
    def reward(self) -> float:
        assert self.evaluation.reward is not None
        return self.evaluation.reward


class TranspositionTable:
    """Maps a state key to its canonical search node.

    The key identified the effective kernel together with its workload, launch config, hardware and toolchain context. If the state is regenerated, its SearchNode and cached evaluation are reused.
    """
    def __init__(self) -> None:
        self._by_key: dict[str, SearchNode] = {}

    def get(self, state_key: str) -> SearchNode | None:
        return self._by_key.get(state_key)

    def add(self, node: SearchNode) -> SearchNode:
        existing = self._by_key.setdefault(node.state_key, node)
        return existing

    def __len__(self) -> int:
        return len(self._by_key)

    def values(self):
        return self._by_key.values()
